@hostname = http://localhost:8000
# @hostname = https://finder.similater.com/car
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjk1MDQ0MTI3LCJleHAiOjE2OTUwNDc3MjcsIm5iZiI6MTY5NTA0NDEyNywianRpIjoiazdrajVqZm5SS1dsMTdCcyIsInN1YiI6IjIiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.HSFj6jxJpBRiHt_eaDUqPKPKCLpooIFy6W95_wgjsOI
@path = /api/meeting


### new  meeting

post {{hostname}}{{path}}/new-client-therapy-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":3,
    "reason":"hello",
    "additional":"",
    "apt_date":"2002-07-08",
    "start_time":"00:00:00",
    "end_time":"03:00:00"
}

### Reserved times

post {{hostname}}{{path}}/reserved-times 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":3,
    "apt_date":"2002-07-03"
}

### my meetings

get {{hostname}}{{path}}/my-meetings
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### new trainer client meeting

post {{hostname}}{{path}}/new-trainer-client-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title":"fdfsf",
    "description":"fsff",
    "clients" : [3,3],
    "trainer_id": 2,
    "start_time":"19.00.00"
}


