@hostname = http://localhost:8000/
# @hostname = https://finder.similater.com/car
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvL2FwaS9sb2dpbiIsImlhdCI6MTY5NTIyMzU5NywiZXhwIjoxNzI0NzIyMzU5NywibmJmIjoxNjk1MjIzNTk3LCJqdGkiOiJObDNTaXFDU3RxMjNJMVZaIiwic3ViIjoiMiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.m_b4akLPX2gof6pBKsPq9l59pAmSU0yLb5eCzCx3jCg
@path = /api/meeting


### new  meeting

post {{hostname}}{{path}}/new-client-therapy-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":2,
    "reason":"hello",
    "additional":"",
    "apt_date":"2002-07-10",
    "start_time":"03:00:00",
    "end_time":"05:00:00"
}

### Reserved times

post {{hostname}}{{path}}/reserved-times 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":3,
    "apt_date":"2002-07-03"
}

### my meetings

get {{hostname}}{{path}}/my-meetings
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### new trainer client meeting

post {{hostname}}{{path}}/new-trainer-client-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title":"fdfsf",
    "description":"fsff",
    "clients" : [3,3],
    "trainer_id": 2,
    "start_time":"19.00.00"
}


###meeting call invoke

post {{hostname}}{{path}}/voice-call/actions/invoke
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "from":"2",
    "to":"2",
    "channel" : "test"
}
