@hostname = http://localhost:8000/
# @hostname = https://finder.similater.com/car
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvL2FwaS9sb2dpbiIsImlhdCI6MTY5NTEzNDkzNSwiZXhwIjoxNjk1MTM4NTM1LCJuYmYiOjE2OTUxMzQ5MzUsImp0aSI6IkRKRHZRcHpKUXJMcDdEc20iLCJzdWIiOiIyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.ch9Nx0etJCKoBqFa8W9YUXL_5zwZ1-DVUIAvS-9eOr4
@path = /api/meeting


### new  meeting

post {{hostname}}{{path}}/new-client-therapy-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":2,
    "reason":"hello",
    "additional":"",
    "apt_date":"2002-07-10",
    "start_time":"03:00:00",
    "end_time":"05:00:00"
}

### Reserved times

post {{hostname}}{{path}}/reserved-times 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapy_id":3,
    "apt_date":"2002-07-03"
}

### my meetings

get {{hostname}}{{path}}/my-meetings
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### new trainer client meeting

post {{hostname}}{{path}}/new-trainer-client-meeting 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title":"fdfsf",
    "description":"fsff",
    "clients" : [3,3],
    "trainer_id": 2,
    "start_time":"19.00.00"
}


