@hostname = http://13.215.175.150:8081
# @hostname = https://finder.similater.com/car
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvL2FwaS9sb2dpbiIsImlhdCI6MTY5NTEyMzkwMCwiZXhwIjoxNjk1MTI3NTAwLCJuYmYiOjE2OTUxMjM5MDAsImp0aSI6Iko4UHhMcVlTcXlCMzlMUGkiLCJzdWIiOiIyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.DvvuPrjxJmCMf7AOuGiDS7SqyMXT2_NAcXu-6_OG1Qw
@path = /api/meeting


### new  meeting

post {{hostname}}{{path}}/voice-call/actions/rtcToken
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "channelName":"test"
}





