@hostname = http://localhost:8000
# @hostname = https://finder.similater.com/car
@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvL2FwaS9sb2dpbiIsImlhdCI6MTY5NTE3MTA5MywiZXhwIjoxNjk1MTc0NjkzLCJuYmYiOjE2OTUxNzEwOTMsImp0aSI6Imd3MmxiUlJZNTczT0RLY0MiLCJzdWIiOiIyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.S03tj5HsHWqgJqxGx6Gxw3VtKfkHhLwE-67ywBmmuyg
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJyb2xlIjoxLCJsb2NhdGlvbiI6MCwiaWF0IjoxNjY2OTU2MTg4LCJleHAiOjQ2NjY5NTYxODh9.-MKOr7FBjbySpLhlCymMgtYmoiuz1mBll4JcbGpbQxM
@path = /api/therapy


### therapy Add

post {{hostname}}{{path}}/add 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "image_1":Before Img,
    "image_2": After Img,
    "name":"sample",
    "age":2,
    "desc":"sample",
    "point_1":"sample",
    "point_2":"sample",
    "point_3":"sample",
    "point_4":"sample"
}

### therapy update

post {{hostname}}{{path}}/update 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "therapyId":1,
    "image_1":Before Img,
    "image_2": After Img,
    "name":"sample",
    "age":2,
    "desc":"sample",
    "point_1":"sample",
    "point_2":"sample",
    "point_3":"sample",
    "point_4":"sample"
}


### therapy list

post {{hostname}}{{path}}/search 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "search":""
}


### therpy search

get {{hostname}}{{path}}/list 
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### therapy list

get {{hostname}}{{path}}/view 
Content-Type: application/json
Authorization: Bearer {{accessToken}}