@hostname = http://18.141.225.158
# @hostname = https://finder.similater.com/car
@accessToken =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNjkzOTMxNjU2LCJleHAiOjE2OTM5MzUyNTYsIm5iZiI6MTY5MzkzMTY1NiwianRpIjoib0JmVm1mYURoSkZZYk5pMSIsInN1YiI6IjIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.GjpSQf3EEXWX9vpCXqL764dWwcFgPLOOrmt0zzZqewo

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxLCJyb2xlIjoxLCJsb2NhdGlvbiI6MCwiaWF0IjoxNjY2OTU2MTg4LCJleHAiOjQ2NjY5NTYxODh9.-MKOr7FBjbySpLhlCymMgtYmoiuz1mBll4JcbGpbQxM
@path = /api


### therapy Add

post {{hostname}}{{path}}/login 
Content-Type: application/json

{
    "email":"ruchira@client.test",
    "password": "1234"
}

### user rgister
post {{hostname}}{{path}}/register 
Content-Type: application/json

{
            "name":"Nuwan Konara",
            "email" : "client@similater.com",
            "password" : "similater",
            "confirm":"similater",
            "role" :"client",
            "phone" : "075444553",
            "nic" :"12333",
            "gender": "male",
            "birthday":"2002-07-03",
            "country_code" : "lk",
            "currency":"rs",
            "address":"12",
            "emergency_contact_name":"nuwan",
            "emergency_contact_phone": "0741554394"
}

### forgot password

post {{hostname}}{{path}}/forgot-password 
Content-Type: application/json

{
    "email":"helloworld"
}